### ISSUE TITLE
Follow up with unresolved review comments

### ISSUE THREAD

**Issue by abhayks1** [OpenST/openst.js#136]
PR #134 

**txOptions.gasPrice Validation:**

  The validation should also be applied in all 3 interaction layers. Instead of replicating this validation in every method we can refactor to a common place. Will update in the ticket.

**r, s, v validation**

Apply this validation in all interact methods which accepts r, s, v as input.

**TokenHolder.js**

Add getter for token address, sessionWindow, sessionKeys, tokenRules, owner address.

**TokenRules.js**

Add getter for areDirectTransfersEnabled and token

**GnosisSafe.js**

Validation check the number of signatures provided should match the threshold.

**Comment by benjaminbollen** [comment]
should ContractInteract of `PricerRule` not be exposed too?

**Comment by abhayks1** [comment]
Agree! 
Committed a change which addresses this point in PR #134 
https://github.com/OpenST/openst.js/pull/134/commits/b5ab83e6656aa9d198f49b976ade3ae812cbc18f
