### ISSUE TITLE
Implement TokenHolder executeRedemption interaction layer method

### ISSUE THREAD

**Issue by abhayks1** [OpenST/openst.js#142]
For redeem to initiate through TokenHolder, Below interaction layer method needs to be implemented:
- executeRedemption.
Interface looks like below:
```
function executeRedemption(
        to,
        data,
        nonce,
        r,
        s,
        v,
       txOptions
    )
```
- getCoGatewayRedeemExecutableData
   Constructs executable data for CoGateway.redeem method.

**Comment by benjaminbollen** [comment]
Consideration / not part of this ticket:
for TokenHolder.executeRedemption the relayer needs to give the user the hashlock so that it can be part of `data` and signed by the user.  This is a different ticket outside of the contractInteract of TokenHolder though.

**Comment by benjaminbollen** [comment]
had some minor comments;
